# Generated by Django 4.0.3 on 2022-03-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_match_team_1_remove_match_team_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_set',
            field=models.CharField(max_length=200),
        ),
    ]
