# Generated by Django 4.0.5 on 2022-06-15 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_comment_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.team'),
            preserve_default=False,
        ),
    ]
